### ISSUE TITLE
Update the link for translation in the README.md file

### ISSUE THREAD

**Issue by Umeaboy** [Aptoide/aptoide-client-v8#114]
The link to translate Aptoide is broken. Please fix it so people would know where to translate.
For some reason it got removed from weblate.org as well.

**Comment by AptRute** [comment]
Hello Umeaboy,

The project got moved to a different platform and we're still working around some domain issues. What language did you use to help with? I will send you a link for you to join the project. 

Thanks a lot!

**Comment by Umeaboy** [comment]
Swedish.

Den 22 juni 2017 11:14 skrev "AptRute" <notifications@github.com>:

**Comment by AptRute** [comment]
Hello again,

You can join us on this link:
http://translate.aptoide.com/project/aptoide-mobile/invite?d=9575p465n607d3u4c59373s4r4m4f3

Please note that a lot of the string IDs (and actual strings) have changed considerably since we moved from Weblate, so there aren't many translations that we can recover from three months ago. Don't hesitate in getting in touch via Crowdin whenever you need some help or support.

Thanks a lot for getting involved with Aptoide.
