### ISSUE TITLE
[9.0.0.0] Refreshing app list causes app to slow down, freeze, and then crash

### ISSUE THREAD

**Issue by TacoTheDank** [Aptoide/aptoide-client-v8#588]
and the weird thing is that it started doing this today, when it was perfectly fine yesterday :/

AT&T Samsung Galaxy S4
Android Lollipop 5.0.1
480 dpi (screen code: 300/480 according to Aptoide)
Tell me if there's other things I could provide that could be useful

I've tried clearing data, restarting phone (my phone's been acting up lately but I don't think that's related)
Here's a recording of it.
https://streamable.com/o3g3t

**Comment by jdandrade** [comment]
Hello.

Thank you for the feedback and the highly detailed information you provided us.

Can you provide us the model number of your device? You can find this under settings > about device > model number. This will help us search for the stack trace in our crash logs.

Best regards,
João Andrade

**Comment by TacoTheDank** [comment]
oh sure its SAMSUNG-SGH-I337

**Comment by jdandrade** [comment]
Thank you very much for the fast response, the team will look into this problem and we will update you with the situation when we make any progress.

**Comment by TacoTheDank** [comment]
kk

**Comment by hirenshah** [comment]
This has been an issue since the v9 Dev versions as well. I've reported it multiple times but nothing has progressed 🙁

**Comment by TacoTheDank** [comment]
yeah it seems it hasn't been fixed yet, which is kinda understandable considering how much code this app has, but still

**Comment by jdandrade** [comment]
This issue is currently being fixed by the team. There are some problems regarding the integration of the Download library that we use - we are trying to fix this the best way we can so it doesn't happen again in the future.

Thank you for your patience, we will update this when we know in which version the fix will be applied.

**Comment by TacoTheDank** [comment]
tbh i did prefer the v8 update screen over the v9 update screen, but whatever i guess

**Comment by jdandrade** [comment]
The reason we changed from what it was in v8 to what you can see now in v9 was because of the way we changed the navigation. With the bottom navigation, we wanted to achieve the minimum number of menus possible and the decision to merge the updates with the downloads tab was natural. 
The complexity of having both on the same screen is the reason why we have so much performance issues today on the Apps menu item. 

I do agree that the update screen feels a bit unfinished because we wanted to reduce all the clutter to keep it minimal, but this will be reevaluated and there are already some minor adjustements in the backlog that we might apply, depending on other priorities.

**Comment by jdandrade** [comment]
Hello,

This should be fixed in the latest version of Aptoide. Please open a new issue if you see it happening again.

**Comment by TacoTheDank** [comment]
Yay
